name: jobs-retrospection

on:
  workflow_dispatch:

jobs:
  deploy_1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          false

  deploy_2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
  
  retrospection:
    if: ${{ always() }}
    needs: [deploy_1, deploy_2]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJson(needs) }}"
