name: meta_deploy

on: 
  pull_request:
    branches: [main]
    paths:
      - environments/**/deploy-config.json
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # Create 3 matrices for each environment
  # units = [], how to add each value with metadata? version, changed 
  units:
    runs-on: ubuntu-latest
    outputs:
      units: ${{ steps.output.outputs.units }}
      units_conf: ${{ steps.output.outputs.units_conf }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # TODO: otherwise git show --pretty="" --name-only HEAD show all files

      # Implement something like dorny/paths-filter@v2.11.1

      - uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: '1.7'
          force: true

      # TODO: What is environment variable length limit?
      # TODO: environment is mentioned in two places - risk of updating
      - name: Get environments configuration
        run: |
          changed_files=$(git show --pretty="" --name-only HEAD)
          echo "Changed files:"
          echo -e "$changed_files" | sed 's/^/\t/'

          echo 'Create configuration using the schema: {"<unit>": <deploy-config> * {"environment": "", "next_environment": "", "deployed_release_version": ""}}'
          echo '{}' | tee meta-config.json
          for config_file in $(echo "$changed_files" | grep 'deploy-config.json'); do
            unit=$(echo "$config_file" | sed -n 's/environments\/\(.*\)\/\(.*\)\/.*/\2/p')

            echo "Add whole unit deploy config"
            deploy_config=$(jq --raw-output --compact-output '.' $config_file)
            jq --arg deploy_config "$deploy_config" --arg unit "$unit" '. |= . * {$unit: $deploy_config | fromjson}' | tee -a tmp.json && mv tmp.json meta-config.json

            echo "Add meta parameters"
            environment=$(echo "$config_file" | sed -n 's/environments\/\(.*\)\/\(.*\)\/.*/\1/p')
            next_environment=$(jq --raw-output '.next_environment' $(dirname $config_file)/promote-config.json)
            echo "Get previous deployed version only if it is not the first commit in repository and config file exist in previous commit"
            if [[ "$(git log -2 --oneline | wc -l)" == "2" && "$(git ls-tree -r HEAD^ --name-only)" =~ (^|$'\n')"$config_file"($'\n'|$) ]]; then
              deployed_release_version=$(git show HEAD^:$config_file | jq --raw-output '.version')
            fi
            jq --arg environment "$environment" --arg unit "$unit" --arg next_environment "$next_environment" --arg deployed_release_version "$deployed_release_version" \
              '. |= . * {$unit: {"environment": $environment, "next_environment": $next_environment, "deployed_release_version": $deployed_release_version}}' meta-config.json \
              | tee -a tmp.json && mv tmp.json meta-config.json
          done
      
      - name: Set output
        id: output
        run: |
          units_conf=$(jq --compact-output '.' meta-config.json)
          echo "units_conf=$units_conf" | tee -a "$GITHUB_OUTPUT"
          units=$(jq --compact-output 'keys' meta-config.json)
          echo "units=$units" | tee -a "$GITHUB_OUTPUT"

  #####################
  # Units
  #####################

  # Deployment unit
  poc-ndp-helm-chart1:
    needs: [units]
    if: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'] != '' }}
    name: "${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].environment }} : poc-ndp-helm-chart1 : ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].deployed_release_version }} ->  ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].version }}"
    secrets: inherit
    concurrency:
      group: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].environment }}
    uses: oleksandrkudin/poc-ndp-helm-chart1/.github/workflows/deploy.yaml@main
    with:
      environment: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].environment }}
      release_version:  ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].version }}
      next_environment: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].next_environment }}
      app_version: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-helm-chart1'].appVersion }}

  # Tracking unit
  poc-ndp-app1:
    needs: [units, poc-ndp-helm-chart1]
    if: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'] != '' }}
    name: "${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].environment }} : poc-ndp-app1 : ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].deployed_release_version }} ->  ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].version }}"
    secrets: inherit
    concurrency:
      group: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].environment }}
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/null_deploy.yaml@main
    with:
      unit: "poc-ndp-app1"
      environment: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].environment }}
      release_version:  ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].version }}
      next_environment: ${{ fromJson(needs.units.outputs.units_conf)['poc-ndp-app1'].next_environment }}
      deployment_statuses: '["${{ needs.poc-ndp-helm-chart1.result }}"]'


  #####################
  # Dashboard
  #####################

  dashboard:
    if: ${{ always() }}
    needs: [units, poc-ndp-helm-chart1, poc-ndp-app1]
    runs-on: ubuntu-latest
    secrets: inherit
    strategy:
      matrix:
        unit: ${{ fromJson(needs.units.outputs.units) }}
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/job_badge.yaml@main
    with:
      job_result: '${{ needs[matrix.unit].result }}'
      badge_directory: '.github/badges'
      badge_label: '${{ fromJson(needs.units.outputs.units_conf)[matrix.unit].deployed_release_version }} -> ${{ fromJson(needs.units.outputs.units_conf)[matrix.unit].version }}'
      unit: ${{ matrix.unit }}
      environment: ${{ fromJson(needs.units.outputs.units_conf)[matrix.unit].environment }}
