name: meta_deploy

on: 
  push:
    branches: [main]
    paths:
      - environments/**
  workflow_dispatch:

jobs:
  # Create 3 matrices for each environment
  # units = [], how to add each value with metadata? version, changed 
  units:
    runs-on: ubuntu-latest
    outputs:
      dev_units: ${{ steps.output.outputs.dev_units }}
      test_units: ${{ steps.output.outputs.test_units }}
      prod_units: ${{ steps.output.outputs.prod_units }}
      dev_units_config: ${{ steps.output.outputs.dev_units_config }}
      test_units_config: ${{ steps.output.outputs.test_units_config }}
      prod_units_config: ${{ steps.output.outputs.prod_units_config }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # TODO: otherwise git show --pretty="" --name-only HEAD show all files

      # Implement something like dorny/paths-filter@v2.11.1

      - uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: '1.7'
          force: true

      # TODO: What is environment variable length limit?
      # TODO: environment is mentioned in two places - risk of updating
      - name: Get environments configuration
        working-directory: environments
        run: |
          changed_files=$(git show --pretty="" --name-only HEAD)
          echo "Changed files:"
          echo -e "$changed_files" | sed 's/^/\t/'

          echo 'Create configuration using the schema: {"<env>": {"<unit>": {"version": ""}}}'
          echo '{}' | tee meta-config.json
          for config_file in $(find ./ -name config.json); do
            version=$(jq --raw-output '.version' $config_file)
            next_environment=$(jq --raw-output '.next_environment' $config_file)
            unit=$(basename $(dirname $config_file))
            environment=$(basename $(dirname $(dirname $config_file)))
            if [[ "$changed_files" =~ "$(echo $config_file | sed 's/\./environments/')" ]]; then
              changed="true"
            else
              changed="false"
            fi
            jq --arg environment "$environment" --arg unit "$unit" --arg version "$version" --arg next_environment "$next_environment" --arg changed "$changed" \
              '. |= . * {$environment: {$unit: {"version": $version, "next_environment": $next_environment, "changed": $changed}}}' meta-config.json \
              | tee -a tmp.json && mv tmp.json meta-config.json
          done
      
      - name: Set output
        id: output
        working-directory: environments
        run: |
          dev_units=$(jq --compact-output '.dev | keys' meta-config.json)
          test_units=$(jq --compact-output '.test | keys' meta-config.json)
          prod_units=$(jq --compact-output '.prod | keys' meta-config.json)
          dev_units_config=$(jq --compact-output '.dev' meta-config.json)
          test_units_config=$(jq --compact-output '.test' meta-config.json)
          prod_units_config=$(jq --compact-output '.prod' meta-config.json)
          echo "dev_units=$dev_units" | tee -a "$GITHUB_OUTPUT"
          echo "test_units=$test_units" | tee -a "$GITHUB_OUTPUT"
          echo "prod_units=$prod_units" | tee -a "$GITHUB_OUTPUT"
          echo "dev_units_config=$dev_units_config" | tee -a "$GITHUB_OUTPUT"
          echo "test_units_config=$test_units_config" | tee -a "$GITHUB_OUTPUT"
          echo "prod_units_config=$prod_units_config" | tee -a "$GITHUB_OUTPUT"
  
  deploy_dev:
    needs: [units]
    strategy:
      matrix:
        unit: ${{ fromJson(needs.units.outputs.dev_units) }}
    name: deploy_dev (${{ matrix.unit }}, ${{ fromJson(needs.units.outputs.dev_units_config)[matrix.unit]['version'] }})
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-environments/.github/workflows/deploy.yaml@main
    with:
      unit: ${{ matrix.unit }}
      environment: dev
      release_version: ${{ fromJson(needs.units.outputs.dev_units_config)[matrix.unit]['version'] }}  
      next_environment: test
      deployment_required: ${{ fromJson(needs.units.outputs.dev_units_config)[matrix.unit]['changed'] }}
  
  deploy_test:
    needs: [units, deploy_dev]
    strategy:
      matrix:
        unit: ${{ fromJson(needs.units.outputs.test_units) }}
    name: deploy_test (${{ matrix.unit }}, ${{ fromJson(needs.units.outputs.test_units_config)[matrix.unit]['version'] }})
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-environments/.github/workflows/deploy.yaml@main
    with:
      unit: ${{ matrix.unit }}
      environment: test
      release_version: ${{ fromJson(needs.units.outputs.test_units_config)[matrix.unit]['version'] }}  
      next_environment: prod
      deployment_required: ${{ fromJson(needs.units.outputs.test_units_config)[matrix.unit]['changed'] }}

  deploy_prod:
    needs: [units, deploy_test]
    strategy:
      matrix:
        unit: ${{ fromJson(needs.units.outputs.prod_units) }}
    name: deploy_test (${{ matrix.unit }}, ${{ fromJson(needs.units.outputs.prod_units_config)[matrix.unit]['version'] }})
    secrets: inherit    
    uses: oleksandrkudin/poc-ndp-environments/.github/workflows/deploy.yaml@main
    with:
      unit: ${{ matrix.unit }}
      environment: prod
      release_version: ${{ fromJson(needs.units.outputs.prod_units_config)[matrix.unit]['version'] }}  
      next_environment: ""
      deployment_required: ${{ fromJson(needs.units.outputs.prod_units_config)[matrix.unit]['changed'] }}
