name: pr-retrospective

on: 
  pull_request:
    branches: [main]
    paths:
      - environments/**/deploy-config.json

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-retrospective:
    runs-on: ubuntu-latest
    outputs:
      units: ${{ steps.output.outputs.units }}
      units_conf: ${{ steps.output.outputs.units_conf }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
    
      - run: |
          #git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* + 
          ls .git/
          git branch
          echo "File list:"
          git show --pretty="" --name-only origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.head_ref }} | sed 's/^/\t/'
          echo "File content in base branch:"
          git show origin/${{ github.event.pull_request.base.ref }}:environments/dev/poc-ndp-app1/deploy-config.json
          echo "Just 10 commits from HEAD"
          git log -10 --oneline
          echo "git branch --show-current"
          git branch --show-current
          echo "head=${{ github.head_ref }}, ref=${{ github.ref_name }}"
          echo "pr:"
          echo "${{ toJson(github.event.pull_request) }}"